// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    return '<div class="map">\n	<img />\n</div>\n\n<div class="selection-area">\n	<img />\n\n  <div class="scale">\n    <div class="mark"></div>\n    <div class="mark"></div>\n    <div class="mark"></div>\n    <div class="mark"></div>\n    <div class="mark"></div>\n    <div class="mark"></div>\n    <div class="label">100mm</div>\n  </div>\n</div>';
  });

}).call(this);
