// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    return '<div class="scallop score">\n  <div class="description">Total number of<br />scallops marked</div>\n  <div class="count">0</div>\n</div>\n\n<div class="fish score">\n  <div class="description">Total number of<br />fish marked</div>\n  <div class="count">0</div>\n</div>\n\n<div class="seastar score">\n  <div class="description">Total number of<br />seastars marked</div>\n  <div class="count">0</div>\n</div>\n\n<div class="crustacean score">\n  <div class="description">Total number of<br />crustaceans marked</div>\n  <div class="count">0</div>\n</div>\n\n<div class="classifications score">\n  <div class="description">Total number of<br />images classified</div>\n  <div class="count">0</div>\n</div>';
  });

}).call(this);
