// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    return '<div class="errors"></div>\n\n<div class="sign-in">\n  <form>\n    <label>\n      <span>User name</span>\n      <input type="text" name="username" />\n    </label>\n\n    <label>\n      <span>Password</span>\n      <input type="password" name="password" />\n    </label>\n\n    <button type="submit">Sign in</button>\n  </form>\n</div>\n\n<div class="waiting">Signing in...</div>\n\n<div class="sign-out">\n  <p>Currently logged in as <strong class="current"></strong>. <button>Sign out</button></p>\n</div>';
  });

}).call(this);
