// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var $, BaseClassifier, Classifier, template, tutorialSteps;
    $ = require('jQuery');
    BaseClassifier = require('zooniverse/controllers/Classifier');
    template = require('views/Classifier');
    tutorialSteps = require('tutorialSteps');
    Classifier = (function(_super) {

      __extends(Classifier, _super);

      Classifier.prototype.template = template;

      Classifier.prototype.tutorialStep = tutorialSteps;

      Classifier.prototype.events = $.extend({
        'click .example': function() {
          return alert('Example clicked');
        }
      }, BaseClassifier.prototype.events);

      Classifier.prototype.elements = $.extend({
        '.example': 'exampleNode'
      }, BaseClassifier.prototype.elements);

      function Classifier() {
        Classifier.__super__.constructor.apply(this, arguments);
      }

      return Classifier;

    })(BaseClassifier);
    return module.exports = Classifier;
  });

}).call(this);
