// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var $, BaseProfile, Profile;
    $ = require('jQuery');
    BaseProfile = require('zooniverse/controllers/Profile');
    Profile = (function(_super) {

      __extends(Profile, _super);

      Profile.prototype.events = $.extend({
        'click .example': function() {
          return alert('Example clicked');
        }
      }, BaseProfile.prototype.events);

      Profile.prototype.elements = $.extend({
        '.example': 'exampleNode'
      }, BaseProfile.prototype.elements);

      function Profile() {
        Profile.__super__.constructor.apply(this, arguments);
      }

      return Profile;

    })(BaseProfile);
    return module.exports = Profile;
  });

}).call(this);
