// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var App, Classifier, Profile, Project, Subject, Workflow, config, tutorialSteps;
    config = require('zooniverse/config');
    App = require('zooniverse/models/App');
    Project = require('zooniverse/models/Project');
    Workflow = require('zooniverse/models/Workflow');
    Subject = require('zooniverse/models/Subject');
    Classifier = require('controllers/Classifier');
    tutorialSteps = require('tutorialSteps');
    Profile = require('controllers/Profile');
    config.set({
      name: 'IRDCs',
      slug: 'irdcs',
      description: 'PROJECT DESCRIPTION',
      domain: 'irdcs.org',
      talkHost: 'http://talk.irdcs.org',
      googleAnalytics: 'UA-0000000-00',
      cartoUser: 'CARTODB USER',
      cartoApiKey: 'CARTODB API KEY',
      cartoTable: 'CARTODB TABLE'
    });
    config.set({
      app: new App({
        el: '.irdcs.app',
        languages: ['en'],
        projects: [
          new Project({
            id: 'PROJECT ID',
            workflows: [
              new Workflow({
                id: 'WORKFLOW ID',
                controller: new Classifier({
                  el: '[data-page="classify"]',
                  tutorialSteps: tutorialSteps
                }),
                tutorialSubjects: [
                  new Subject({
                    location: 'TUTORIAL SUBJECT LOCATION',
                    coords: [0, 0],
                    workflow: {}
                  })
                ]
              })
            ]
          })
        ]
      })
    });
    return config.set({
      profile: new Profile({
        el: '[data-page="profile"]'
      })
    });
  });

}).call(this);
