// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var Step;
    Step = require('zooniverse/controllers/Tutorial').Step;
    return module.exports = [];
  });

}).call(this);
