// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    return module.exports = "<div class=\"example\">\n  <p>This is the classification interface.</p>\n</div>";
  });

}).call(this);
