// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var ProfileFavorite, Spine, template;
    Spine = require('Spine');
    template = require('views/ProfileFavorite');
    ProfileFavorite = (function(_super) {

      __extends(ProfileFavorite, _super);

      ProfileFavorite.favorite = null;

      ProfileFavorite.prototype.template = template;

      function ProfileFavorite() {
        ProfileFavorite.__super__.constructor.apply(this, arguments);
        this.html(this.template(this.favorite));
        this.favorite.bind('destroy', this.release);
      }

      return ProfileFavorite;

    })(Spine.Controller);
    return module.exports = ProfileFavorite;
  });

}).call(this);
