// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var L, Sky, Spine;
    Spine = require('Spine');
    L = require('Leaflet');
    Sky = (function(_super) {

      __extends(Sky, _super);

      Sky.prototype.mapOptions = {
        attributionControl: true,
        worldCopyJump: false
      };

      function Sky() {
        this.createMap = __bind(this.createMap, this);
        Sky.__super__.constructor.apply(this, arguments);
        this.createMap();
      }

      Sky.prototype.createMap = function() {
        var layer, map;
        map = L.map('banner', this.mapOptions).setView([14, 0], 0);
        map.attributionControl.setPrefix('');
        layer = L.tileLayer('/tiles/#{tilename}.jpg', {
          minZoom: 0,
          maxZoom: 8,
          attribution: 'Robert Gendler - The Andromeda Galaxy (M31) &copy; 2005',
          noWrap: true
        });
        layer.getTileUrl = function(tilePoint) {
          var x, y, z;
          z = this._getZoomForUrl();
          x = tilePoint.x;
          y = tilePoint.y;
          return "http://www.andromedaproject.org.s3.amazonaws.com/tiles/F475_B01/" + z + "/" + x + "/" + y + ".png";
        };
        return layer.addTo(map);
      };

      return Sky;

    })(Spine.Controller);
    return module.exports = Sky;
  });

}).call(this);
