// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports, module) {
    var dev, ids;
    dev = require('zooniverse/config').dev;
    dev = true;
    if (dev) {
      ids = {
        project: 'andromeda',
        workflow: '5052085f516bcb6b8a000003',
        tutorialSubject: '509935796aa0e064b6000001'
      };
    } else {
      ids = {
        project: 'andromeda',
        workflow: '5052085f516bcb6b8a000003',
        tutorialSubject: '509935796aa0e064b6000001'
      };
    }
    return module.exports = ids;
  });

}).call(this);
