// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require, exports, module) {
    var dev, ids;
    dev = require('zooniverse/config').dev;
    if (dev) {
      ids = {
        project: 'andromeda',
        workflow: '50be4f973ae7409761000001',
        tutorialSubject: '50b781751a320e4aac000001'
      };
    } else {
      ids = {
        project: 'andromeda',
        workflow: '50be4f973ae7409761000001',
        tutorialSubject: '50b781751a320e4aac000001'
      };
    }
    return module.exports = ids;
  });

}).call(this);
