// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var Sample;
    Sample = [
      {
        coords: [0, 0],
        location: {
          standard: "subjects/standard/B09-F11_1.jpg"
        }
      }, {
        coords: [0, 0],
        location: {
          standard: "subjects/standard/B09-F11_2.jpg"
        }
      }, {
        coords: [0, 0],
        location: {
          standard: "subjects/standard/B09-F11_3.jpg"
        }
      }, {
        coords: [0, 0],
        location: {
          standard: "subjects/standard/B09-F11_4.jpg"
        }
      }, {
        coords: [0, 0],
        location: {
          standard: "subjects/standard/B09-F11_5.jpg"
        }
      }
    ];
    return module.exports = Sample;
  });

}).call(this);
