// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require, exports, module) {
    var $, translations;
    $ = require('jQuery');
    translations = require('translations');
    return module.exports = {
      delay: function(duration, callback) {
        if (typeof duration === 'function') {
          callback = duration;
          duration = 0;
        }
        return setTimeout(callback, duration);
      },
      indexOf: function(array, theItem) {
        var anItem, i;
        return (typeof array.indexOf === "function" ? array.indexOf(theItem) : void 0) || ((function() {
          var _i, _len, _results;
          _results = [];
          for (i = _i = 0, _len = array.length; _i < _len; i = ++_i) {
            anItem = array[i];
            if (anItem === theItem) {
              _results.push(i);
            }
          }
          return _results;
        })())[0];
      },
      translate: function(term, wrap, className) {
        var container, language, languages, part, parts, _i, _len;
        if (wrap == null) {
          wrap = 'p';
        }
        if (className == null) {
          className = '';
        }
        container = $("<div></div>");
        languages = translations[term];
        for (language in languages) {
          parts = languages[language];
          if (!(parts instanceof Array)) {
            parts = [parts];
          }
          for (_i = 0, _len = parts.length; _i < _len; _i++) {
            part = parts[_i];
            container.append("<" + wrap + " lang=\"" + language + "\">" + part + "</" + wrap + ">");
          }
        }
        return container.children().addClass(className);
      }
    };
  });

}).call(this);
