// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Project, Spine, config;
    Spine = require('Spine');
    config = require('zooniverse/config');
    Project = (function(_super) {

      __extends(Project, _super);

      Project.configure('Project', 'devID', 'app', 'workflows');

      function Project() {
        var workflow, _i, _len, _ref, _ref1;
        Project.__super__.constructor.apply(this, arguments);
        if (config.dev) {
          this.id = this.devID;
        }
        if ((_ref = this.workflows) == null) {
          this.workflows = [];
        }
        _ref1 = this.workflows;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          workflow = _ref1[_i];
          workflow.project = this;
        }
      }

      return Project;

    })(Spine.Model);
    return module.exports = Project;
  });

}).call(this);
