// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require, exports, module) {
    var Spine, Subject, config;
    Spine = require('Spine');
    config = require('zooniverse/config');
    Subject = (function(_super) {

      __extends(Subject, _super);

      function Subject() {
        this.twitterHref = __bind(this.twitterHref, this);

        this.facebookHref = __bind(this.facebookHref, this);

        this.talkHref = __bind(this.talkHref, this);
        return Subject.__super__.constructor.apply(this, arguments);
      }

      Subject.configure('Subject', 'zooniverseID', 'location', 'coords', 'metadata');

      Subject.fromJSON = function(raw) {
        return this.create({
          id: raw.id,
          zooniverseID: raw.zooniverse_id,
          location: raw.location,
          coords: raw.coords,
          metadata: raw.metadata
        });
      };

      Subject.prototype.talkHref = function() {
        return "" + config.talkHost + "/objects/" + this.zooniverseID;
      };

      Subject.prototype.facebookHref = function() {
        return ("https://www.facebook.com/dialog/feed?\napp_id=" + config.facebookAppId + "&\nlink=" + (this.talkHref()) + "&\npicture=" + (this.location.image || this.location) + "&\nname=" + config.name + "&\ncaption=A Zooniverse citizen science project&\ndescription=" + config.description + "&\nredirect_uri=" + location.href).replace(/\n/g, '');
      };

      Subject.prototype.twitterHref = function() {
        var text;
        text = "I've classified something on " + config.name + "!";
        return "https://twitter.com/share?text=" + text + "&url=" + (this.talkHref());
      };

      return Subject;

    })(Spine.Model);
    return module.exports = Subject;
  });

}).call(this);
